language: python
python:
  - "3.5"
before_install:
    - sudo apt-get update -qq
    - wget http://ftp.sjtu.edu.cn/ubuntu/pool/universe/m/mecab/libmecab2_0.996-1.1_amd64.deb
    - sudo dpkg -i  libmecab2_0.996-1.1_amd64.deb
    - wget http://ftp.sjtu.edu.cn/ubuntu/pool/universe/m/mecab/libmecab-dev_0.996-1.1_amd64.deb
    - sudo dpkg -i libmecab-dev_0.996-1.1_amd64.deb
    - wget http://ftp.sjtu.edu.cn/ubuntu/pool/universe/m/mecab/mecab-utils_0.996-1.1_amd64.deb
    - sudo dpkg -i mecab-utils_0.996-1.1_amd64.deb
    - sudo apt-get install -y mecab-ipadic-utf8
    - pip install pep8
script:
    # Run pep8 on all .py files in all subfolders
    # (I ignore "E402: module level import not at top of file"
    # because of use case sys.path.append('..'); import <module>)
    - find . -name \*.py -exec pep8 {} +
