language: python
python:
  - "3.5"
before_install:
    - sudo apt-get update -qq
    - wget http://ftp.sjtu.edu.cn/ubuntu/pool/universe/m/mecab/libmecab2_0.996-1.1_amd64.deb
    - sudo dpkg -i  libmecab2_0.996-1.1_amd64.deb
    - wget http://ftp.sjtu.edu.cn/ubuntu/pool/universe/m/mecab/libmecab-dev_0.996-1.1_amd64.deb
    - sudo dpkg -i libmecab-dev_0.996-1.1_amd64.deb
    - wget http://ftp.sjtu.edu.cn/ubuntu/pool/universe/m/mecab/mecab-utils_0.996-1.1_amd64.deb
    - sudo dpkg -i mecab-utils_0.996-1.1_amd64.deb
    - sudo apt-get install -y mecab-ipadic-utf8
    - pip install pep8
script:
    - python pep8.py --testsuite testsuite
    - python pep8.py --statistics pep8.py
    - python pep8.py --doctest
