# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_input',
            name='input',
            field=models.URLField(),
        ),
    ]
