# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleclass', '0002_auto_20170507_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_input',
            name='input',
            field=models.CharField(max_length=200),
        ),
    ]
