# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleclass', '0004_auto_20170508_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='text_output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='url_input',
            name='input',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='text_output',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='articleclass.url_input', verbose_name='URL'),
        ),
    ]
