# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleclass', '0005_auto_20170515_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text_output',
            name='url',
        ),
        migrations.DeleteModel(
            name='text_output',
        ),
    ]
