# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleclass', '0006_auto_20170516_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='text_output',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('url', models.ForeignKey(
                                          on_delete=django.db.models.deletion.CASCADE,
                                          related_name='text',
                                          to='articleclass.url_input',
                                          verbose_name='URL')),
            ],
        ),
    ]
