# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleclass', '0007_text_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text_output',
            name='url',
        ),
        migrations.DeleteModel(
            name='text_output',
        ),
        migrations.DeleteModel(
            name='url_input',
        ),
    ]
